apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: test-pod-failure
  namespace: chaos-engineering
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - eshop
    labelSelectors:
      app: eshop-webmvc
