apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: eshop-memory-stress
  namespace: chaos-testing
spec:
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - eshop
    labelSelectors:
      "app": "eshop-webmvc"
  stressors:
    memory:
      workers: 1
      size: "256MB"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: eshop-cpu-stress
  namespace: chaos-testing
spec:
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - eshop
    labelSelectors:
      "app": "eshop-webmvc"
  stressors:
    cpu:
      workers: 1
      load: 80
---
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: eshop-http-delay
  namespace: chaos-testing
spec:
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - eshop
    labelSelectors:
      "app": "eshop-webmvc"
  target: Request
  port: 80
  method: GET
  path: "/*"
  delay: "500ms"
