apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: eshop-pod-chaos
  namespace: eshop
spec:
  action: pod-failure
  mode: one
  duration: "60s"
  selector:
    namespaces:
      - eshop
    labelSelectors:
      app: eshop-webmvc
