apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-publicapi
  namespace: eshop
  labels:
    app: eshop-publicapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-publicapi
  template:
    metadata:
      labels:
        app: eshop-publicapi
    spec:
      containers:
      - name: publicapi
        image: eshopcleveracr.azurecr.io/eshoppublicapi:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: eshop-config
              key: ASPNETCORE_ENVIRONMENT
        - name: UseOnlyInMemoryDatabase
          valueFrom:
            secretKeyRef:
              name: eshop-secrets
              key: UseOnlyInMemoryDatabase
        - name: ConnectionStrings__CatalogConnection
          valueFrom:
            secretKeyRef:
              name: eshop-secrets
              key: ConnectionStrings__CatalogConnection
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-publicapi
  namespace: eshop
  labels:
    app: eshop-publicapi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: eshop-publicapi
