apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: eshop-severe-chaos
  namespace: eshop
spec:
  action: pod-failure
  mode: all
  duration: "120s"
  selector:
    namespaces:
      - eshop
    labelSelectors:
      app: eshop-webmvc
